const header=document.querySelector('.navbar');const menuToggle=document.querySelector('.menu-toggle');const navLinks=document.querySelector('.nav-links');const revealElements=document.querySelectorAll('.reveal');const loader=document.querySelector('#page-loader');const loaderBar=document.querySelector('#loader-bar');const loaderPercent=document.querySelector('#loader-percent');const loaderStatus=document.querySelector('#loader-status');const loaderDetail=document.querySelector('#loader-detail');const cursor=document.querySelector('.custom-cursor');
const updateScrollOffset=()=>document.documentElement.style.setProperty('--header-height',`${header?.offsetHeight||70}px`);updateScrollOffset();window.addEventListener('resize',updateScrollOffset,{passive:true});
const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting)return;entry.target.classList.add('visible');revealObserver.unobserve(entry.target)}),{threshold:.08,rootMargin:'0px 0px -6% 0px'});revealElements.forEach(el=>revealObserver.observe(el));
const closeMenu=()=>{navLinks?.classList.remove('active');menuToggle?.setAttribute('aria-expanded','false')};menuToggle?.addEventListener('click',()=>{const open=navLinks.classList.toggle('active');menuToggle.setAttribute('aria-expanded',String(open))});
navLinks?.querySelectorAll('a').forEach(link=>link.addEventListener('click',event=>{const id=link.getAttribute('href');if(!id?.startsWith('#'))return;const target=document.querySelector(id);if(!target)return;event.preventDefault();closeMenu();const top=target.getBoundingClientRect().top+window.scrollY-(header?.offsetHeight||70);window.scrollTo({top:Math.max(0,top),behavior:'smooth'});history.replaceState(null,'',id)}));
document.addEventListener('click',event=>{if(!navLinks?.classList.contains('active'))return;if(navLinks.contains(event.target)||menuToggle?.contains(event.target))return;closeMenu()});window.addEventListener('keydown',event=>{if(event.key==='Escape')closeMenu()});
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function loadSite(){const start=performance.now(),duration=3000;const resources=['./Hiro.png','./CubiGame.jpg'];let loaded=0;const setProgress=p=>{if(loaderBar)loaderBar.style.width=`${p}%`;if(loaderPercent)loaderPercent.textContent=`${p}%`};await Promise.all(resources.map(url=>new Promise(resolve=>{const img=new Image();img.onload=img.onerror=()=>{loaded++;resolve()};img.src=url})));if(document.fonts)await Promise.race([document.fonts.ready,sleep(500)]);const statuses=['INITIALISATION DES RESSOURCES','CHARGEMENT DES IMAGES','POLICES PRÊTES','INTERFACE PRÊTE','BIENVENUE'];let last=-1;while(performance.now()-start<duration){const p=Math.min(99,Math.floor((performance.now()-start)/duration*100));setProgress(p);const index=Math.min(3,Math.floor(p/25));if(index!==last){last=index;if(loaderStatus)loaderStatus.textContent=statuses[index];if(loaderDetail)loaderDetail.textContent=['Préparation du site','Chargement des images','Préparation de la typographie','Dernières vérifications'][index]}}await new Promise(requestAnimationFrame);setProgress(100);if(loaderStatus)loaderStatus.textContent=statuses[4];if(loaderDetail)loaderDetail.textContent='Chargement terminé';await sleep(120);loader?.classList.add('entering');document.body.classList.remove('is-loading');await sleep(1050);loader?.classList.add('loaded')}
if(loader)loadSite().catch(()=>{document.body.classList.remove('is-loading');loader.classList.add('loaded')});
if(cursor&&window.matchMedia('(pointer:fine)').matches){let mouseX=-100,mouseY=-100,currentX=-100,currentY=-100;document.body.classList.add('cursor-ready');window.addEventListener('mousemove',event=>{mouseX=event.clientX;mouseY=event.clientY;cursor.style.opacity='1'}, {passive:true});const render=()=>{currentX+=(mouseX-currentX)*.3;currentY+=(mouseY-currentY)*.3;cursor.style.left=`${currentX}px`;cursor.style.top=`${currentY}px`;requestAnimationFrame(render)};render();document.addEventListener('mouseover',event=>{if(event.target.closest('a,button,iframe,.skill-card'))cursor.classList.add('active')});document.addEventListener('mouseout',event=>{if(event.target.closest('a,button,iframe,.skill-card'))cursor.classList.remove('active')})}
