const header=document.querySelector('.navbar');const menuToggle=document.querySelector('.menu-toggle');const navLinks=document.querySelector('.nav-links');const revealElements=document.querySelectorAll('.reveal');const loader=document.querySelector('#page-loader');const loaderBar=document.querySelector('#loader-bar');const loaderPercent=document.querySelector('#loader-percent');const loaderStatus=document.querySelector('#loader-status');const loaderDetail=document.querySelector('#loader-detail');const loaderClock=document.querySelector('#loader-clock');const loaderLog=document.querySelector('#loader-log');const cursor=document.querySelector('.custom-cursor');
const updateScrollOffset=()=>document.documentElement.style.setProperty('--header-height',`${header?.offsetHeight||70}px`);updateScrollOffset();window.addEventListener('resize',updateScrollOffset,{passive:true});
const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting)return;entry.target.classList.add('visible');revealObserver.unobserve(entry.target)}),{threshold:.08,rootMargin:'0px 0px -6% 0px'});revealElements.forEach(el=>revealObserver.observe(el));
const closeMenu=()=>{navLinks?.classList.remove('active');menuToggle?.setAttribute('aria-expanded','false')};menuToggle?.addEventListener('click',()=>{const open=navLinks.classList.toggle('active');menuToggle.setAttribute('aria-expanded',String(open))});
navLinks?.querySelectorAll('a').forEach(link=>link.addEventListener('click',event=>{const id=link.getAttribute('href');if(!id?.startsWith('#'))return;const target=document.querySelector(id);if(!target)return;event.preventDefault();closeMenu();const top=target.getBoundingClientRect().top+window.scrollY-(header?.offsetHeight||70);window.scrollTo({top:Math.max(0,top),behavior:'smooth'});history.replaceState(null,'',id)}));
document.addEventListener('click',event=>{if(!navLinks?.classList.contains('active'))return;if(navLinks.contains(event.target)||menuToggle?.contains(event.target))return;closeMenu()});window.addEventListener('keydown',event=>{if(event.key==='Escape')closeMenu()});
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const waitForImage=src=>new Promise(resolve=>{const img=new Image();img.onload=img.onerror=()=>resolve();img.src=src});
const waitForFonts=()=>document.fonts?.ready||Promise.resolve();
const waitForWindowLoad=()=>document.readyState==='complete'?Promise.resolve():new Promise(resolve=>window.addEventListener('load',resolve,{once:true}));
function addLog(text){if(!loaderLog)return;const line=document.createElement('span');line.textContent=`› ${text}`;loaderLog.appendChild(line);while(loaderLog.children.length>6)loaderLog.removeChild(loaderLog.firstChild)}
function updateClock(start){if(!loaderClock)return;const elapsed=Math.floor((performance.now()-start)/1000);const m=String(Math.floor(elapsed/60)).padStart(2,'0');const s=String(elapsed%60).padStart(2,'0');loaderClock.textContent=`00:${m}:${s}`}
async function loadSite(){const start=performance.now();const minimumTime=3000;let progress=0;const setProgress=p=>{progress=Math.max(progress,Math.min(100,p));if(loaderBar)loaderBar.style.width=`${progress}%`;if(loaderPercent)loaderPercent.textContent=`${progress}%`};
const clock=setInterval(()=>updateClock(start),100);addLog('vérification du document');
await waitForWindowLoad();setProgress(15);if(loaderStatus)loaderStatus.textContent='DOCUMENT PRÊT';if(loaderDetail)loaderDetail.textContent='Structure chargée';addLog('structure HTML prête');
const images=[...document.images].map(img=>img.currentSrc||img.src).filter(Boolean);const uniqueImages=[...new Set(images)];if(loaderStatus)loaderStatus.textContent='CHARGEMENT DES MÉDIAS';if(loaderDetail)loaderDetail.textContent=`${uniqueImages.length} image(s) détectée(s)`;addLog('chargement des images');await Promise.all(uniqueImages.map(waitForImage));setProgress(55);addLog('images disponibles');
if(loaderStatus)loaderStatus.textContent='CHARGEMENT DES POLICES';if(loaderDetail)loaderDetail.textContent='Typographie';await waitForFonts();setProgress(72);addLog('polices prêtes');
if(loaderStatus)loaderStatus.textContent='PRÉPARATION DE L’INTERFACE';if(loaderDetail)loaderDetail.textContent='Styles et scripts';await sleep(180);setProgress(84);addLog('interface prête');
if(loaderStatus)loaderStatus.textContent='DERNIÈRES VÉRIFICATIONS';if(loaderDetail)loaderDetail.textContent='Connexion terminée';await sleep(180);setProgress(94);addLog('vérification terminée');
while(performance.now()-start<minimumTime){updateClock(start);const elapsed=performance.now()-start;const p=94+Math.floor(Math.min(5,(elapsed-(minimumTime-500))/100));if(elapsed>minimumTime-500)setProgress(Math.min(99,p));await new Promise(requestAnimationFrame)}
clearInterval(clock);setProgress(100);if(loaderStatus)loaderStatus.textContent='BIENVENUE';if(loaderDetail)loaderDetail.textContent='Chargement terminé';addLog('site prêt');await sleep(180);loader?.classList.add('entering');document.body.classList.remove('is-loading');await sleep(1100);loader?.classList.add('loaded')}
if(loader)loadSite().catch(()=>{document.body.classList.remove('is-loading');loader.classList.add('loaded')});
if(cursor&&window.matchMedia('(pointer:fine)').matches){const trail=[];const trailCount=12;for(let i=0;i<trailCount;i++){const dot=document.createElement('i');dot.className='cursor-trail';dot.style.opacity='0';document.body.appendChild(dot);trail.push({el:dot,x:-100,y:-100});}let mouseX=-100,mouseY=-100,currentX=-100,currentY=-100;document.body.classList.add('cursor-ready');window.addEventListener('mousemove',event=>{mouseX=event.clientX;mouseY=event.clientY;cursor.style.opacity='1';},{passive:true});const render=()=>{currentX+=(mouseX-currentX)*.34;currentY+=(mouseY-currentY)*.34;cursor.style.left=`${currentX}px`;cursor.style.top=`${currentY}px`;let tx=currentX,ty=currentY;trail.forEach((point,index)=>{const ease=.28-(index*.012);point.x+=(tx-point.x)*ease;point.y+=(ty-point.y)*ease;point.el.style.left=`${point.x}px`;point.el.style.top=`${point.y}px`;point.el.style.opacity=String(.58*(1-index/trailCount));tx=point.x;ty=point.y});requestAnimationFrame(render)};render();document.addEventListener('mouseover',event=>{if(event.target.closest('a,button,iframe,.skill-card,.collab-card'))cursor.classList.add('active')});document.addEventListener('mouseout',event=>{if(event.target.closest('a,button,iframe,.skill-card,.collab-card'))cursor.classList.remove('active')})}
